version: '3'
services:
  
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        target: server
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - ./server:/app/src
    command: npm start
