version: '3'
services:
  mongodb:
    image: bitnami/mongodb
    container_name: mongodb
    ports:
      - 27019:27017
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_DATABASE=study-together-db
      - MONGODB_ROOT_PASSWORD=root
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        target: server
    depends_on:
      - mongodb
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - ./server/:/app/
    command: npm start
